#!/bin/bash
# Guided setup for the multicast relay.
#
# Asks which interfaces to use, the multicast source, the groups to relay,
# and whether to relay all UDP ports or only specific ones. Writes
# /opt/mcast-relay/relay.conf, generates a scoped nftables ruleset
# (default-deny; only the configured groups/ports may cross), validates
# the config, and enables the relay plus the hourly health check.
#
# Usage:
#   sudo mcast-relay-setup              # interactive wizard
#   sudo mcast-relay-setup <file>       # apply a prepared relay.conf, no prompts
#
# Safe to re-run: the previous relay.conf is backed up with a timestamp.

set -u

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

INSTALL_DIR=/opt/mcast-relay
CONF=$INSTALL_DIR/relay.conf
NFT_CONF=/etc/nftables.conf
SERVICE=mcast-relay

die() { echo -e "${RED}$1${NC}" >&2; exit 1; }

[ "$EUID" -eq 0 ] || die "Run as root: sudo mcast-relay-setup"

# ------------------------------------------------------------- apply config

apply_sysctl() {
    # Targeted, idempotent (installer also drops the persistent file).
    sysctl -q -w net.ipv4.ip_forward=1
    sysctl -q -w net.ipv4.conf.all.rp_filter=0
    sysctl -q -w net.ipv4.conf.default.rp_filter=0
    sysctl -q -w net.ipv4.conf.all.force_igmp_version=2
    sysctl -q -w net.ipv4.igmp_max_memberships=100
}

# Turn a GROUPS or PORTS spec into an nft set expression. Always braces —
# ranges (a-b) are only valid inside set literals.
#   "239.1.1.1-239.1.1.39"             -> "{ 239.1.1.1-239.1.1.39 }"
#   "239.1.1.5,239.2.2.1-239.2.2.9"     -> "{ 239.1.1.5, 239.2.2.1-239.2.2.9 }"
nft_expr() {
    local spec="${1// /}"
    echo "{ ${spec//,/, } }"
}

write_nftables() {
    local gex pe rule
    gex=$(nft_expr "$GROUPS")
    if [ "$PORT_POLICY" = "all" ]; then
        rule="ip daddr $gex accept"
    else
        pe=$(nft_expr "$PORTS")
        rule="ip daddr $gex udp dport $pe accept"
    fi

    cat > "$NFT_CONF" << EOF
#!/usr/sbin/nft -f
flush ruleset

# Generated by mcast-relay-setup. Multicast-only forwarding, default deny.
# Only the configured groups (and ports, if restricted) may cross this box.
# ALL other traffic — unicast included — between the two segments is dropped.
table inet relay {
    chain forward {
        type filter hook forward priority 0; policy drop;
        $rule
    }
}
EOF
}

apply_config() {
    echo ""
    echo -e "${YELLOW}Validating and applying...${NC}"

    # 1. Config file (with backup of any previous one)
    if [ -f "$CONF" ]; then
        cp "$CONF" "$CONF.bak.$(date +%Y%m%d%H%M%S)"
        echo "  Previous config backed up."
    fi

    # 2. Validate the config through the relay itself before touching anything
    python3 "$INSTALL_DIR/mcast-relay.py" --check \
        || die "Config validation failed — nothing was changed."

    # 3. nftables ruleset: check syntax, then load
    write_nftables
    nft -c -f "$NFT_CONF" || die "nftables ruleset failed syntax check."
    systemctl restart nftables || die "Failed to restart nftables."
    nft list ruleset | grep -q "table inet relay" \
        || die "nftables ruleset did not load (no 'table inet relay')."
    echo "  nftables: scoped relay ruleset active."

    # 4. Kernel settings
    apply_sysctl
    echo "  sysctl: forwarding enabled, rp_filter off, IGMPv2, memberships=100."

    # 5. Relay + supervision (enabled only now, after a valid setup)
    systemctl enable --now "$SERVICE"
    systemctl restart "$SERVICE"
    systemctl enable --now mcast-relay-check.timer 2>/dev/null || true
    sleep 2

    systemctl is-active --quiet "$SERVICE" \
        || { journalctl -u "$SERVICE" -n 10 --no-pager; \
             die "Relay did not start — see journal above."; }

    echo ""
    echo -e "${GREEN}=== Setup complete ===${NC}"
    echo ""
    echo "  Config:      $CONF"
    echo "  Firewall:    $NFT_CONF"
    echo "  Service:     $SERVICE (enabled, restarting on failure)"
    echo "  Health check: mcast-relay-check.timer (hourly)"
    echo ""
    journalctl -u "$SERVICE" -n 3 --no-pager
    echo ""
    echo -e "${YELLOW}Verify with real traffic (runbook section 10):${NC}"
    echo "  TTL must DECREMENT across the relay — identical TTL on both"
    echo "  sides means you're looking at a flooded copy, not a forward."
    echo ""
    echo "    tcpdump -i <src-if>  -nnv -c 5 host ${GROUPS%%,*}"
    echo "    tcpdump -i <dst-if>  -nnv -c 5 host ${GROUPS%%,*}"
    echo ""
    echo "  And re-test the unicast block from a THIRD host on the source"
    echo "  VLAN — a ping from the relay itself proves nothing."
}

write_conf() {
    cat > "$CONF" << EOF
# relay.conf — generated by mcast-relay-setup $(date -Is)
# Re-run 'sudo mcast-relay-setup' to change; previous files are kept as .bak.*

# Local IP on the source-facing interface (multicast sender side)
IN_IF=$IN_IF
# Local IP on the receiver-facing interface
OUT_IF=$OUT_IF
# Multicast sender's unicast IP — static (S,G) key. Get it reserved/static.
SOURCE=$SOURCE
# Groups to relay: single, comma list, or hyphen range
GROUPS=$GROUPS
# Port policy: all | list   (enforced by nftables, not the relay)
PORT_POLICY=$PORT_POLICY
# UDP ports/ranges when PORT_POLICY=list
PORTS=$PORTS
EOF
}

# -------------------------------------------------------- interface picking

choose_iface() {
    local prompt="$1" pick n
    n=${#IF_ROWS[@]}
    while true; do
        echo ""
        echo "Detected IPv4 interfaces:"
        local i=1 row
        for row in "${IF_ROWS[@]}"; do
            echo "  [$i] ${row%% *}   ${row#* *}"
            i=$((i + 1))
        done
        read -r -p "$prompt [1-$n]: " pick
        if [[ "$pick" =~ ^[0-9]+$ ]] && [ "$pick" -ge 1 ] && [ "$pick" -le "$n" ]; then
            CHOSEN=${IF_ROWS[$((pick - 1))]}
            return
        fi
        echo -e "${RED}  Invalid selection, try again.${NC}"
    done
}

iface_ip() { local r="$1"; r="${r#* }"; echo "${r%%/*}"; }

# ------------------------------------------------------- non-interactive mode

if [ $# -ge 1 ]; then
    [ -f "$1" ] || die "Not a file: $1"
    # relay.conf is plain KEY=VALUE — source it.
    # shellcheck disable=SC1090
    . "$1"
    for k in IN_IF OUT_IF SOURCE GROUPS; do
        [ -n "${!k:-}" ] || die "$1 is missing $k="
    done
    PORT_POLICY="${PORT_POLICY:-all}"
    PORTS="${PORTS:-}"
    write_conf
    apply_config
    exit 0
fi

# ------------------------------------------------------------ guided wizard

echo -e "${GREEN}=== Multicast Relay — Guided Setup ===${NC}"
echo ""
echo "This configures which interfaces, source, groups, and ports the"
echo "relay forwards. Everything else stays firewalled shut."

mapfile -t IF_ROWS < <(ip -br -4 addr show | awk '$2=="UP" && $3 ~ /^[0-9]+\./ {print $1" "$3}')
[ "${#IF_ROWS[@]}" -ge 2 ] \
    || die "Need at least two UP interfaces with IPv4 addresses. Fix addressing first."

# --- Step 1: interfaces ---
choose_iface "Interface facing the multicast SOURCE (e.g. the paging server VLAN)"
SRC_ROW=$CHOSEN
IN_IF=$(iface_ip "$SRC_ROW")

while true; do
    choose_iface "Interface facing the RECEIVERS"
    DST_ROW=$CHOSEN
    if [ "$DST_ROW" != "$SRC_ROW" ]; then break; fi
    echo -e "${RED}  Source and receiver interfaces must differ.${NC}"
done
OUT_IF=$(iface_ip "$DST_ROW")

# --- Step 2: multicast source ---
echo ""
echo "The multicast sender's UNICAST IP (e.g. the Nyquist C4000 server)."
echo "This is a static (S,G) key: if that address ever changes, forwarding"
echo -e "stops ${RED}silently${NC}. Get a DHCP reservation or static assignment for it."
while true; do
    read -r -p "Multicast source IP: " SOURCE
    [[ "$SOURCE" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] && break
    echo -e "${RED}  Enter a valid IPv4 address.${NC}"
done

# --- Step 3: groups ---
echo ""
read -r -p "Multicast groups to relay (single, comma list, or range) [239.1.1.1-239.1.1.39]: " GROUPS
GROUPS="${GROUPS:-239.1.1.1-239.1.1.39}"

# --- Step 4: port policy ---
echo ""
echo "Port policy:"
echo "  [1] ALL UDP ports in these groups  (recommended for paging audio —"
echo "      RTCP comes along free, and per-zone port changes don't break it)"
echo "  [2] ONLY specific UDP ports"
while true; do
    read -r -p "Choose [1-2, default 1]: " pol
    pol="${pol:-1}"
    if [ "$pol" = "1" ]; then PORT_POLICY=all; PORTS=""; break; fi
    if [ "$pol" = "2" ]; then
        while true; do
            read -r -p "UDP ports to relay (comma-separated, ranges ok, e.g. 5002,5003,5010-5013): " PORTS
            ok=1
            IFS=',' read -ra tok <<< "$PORTS"
            for t in "${tok[@]}"; do
                t="${t// /}"
                [[ "$t" =~ ^[0-9]+(-[0-9]+)?$ ]] || { ok=0; break; }
                [ "$t" -ge 1 ] && [ "$t" -le 65535 ] 2>/dev/null || { ok=0; break; }
            done
            [ "$ok" = "1" ] && { PORT_POLICY=list; break; }
            echo -e "${RED}  Ports must be numbers or number ranges, 1-65535.${NC}"
        done
        break
    fi
done

# --- Summary + confirm ---
echo ""
echo -e "${GREEN}=== Review ===${NC}"
echo "  Source interface : ${SRC_ROW%% *}   IN_IF=$IN_IF"
echo "  Receiver iface   : ${DST_ROW%% *}   OUT_IF=$OUT_IF"
echo "  Multicast source : $SOURCE"
echo "  Groups           : $GROUPS"
if [ "$PORT_POLICY" = "all" ]; then
    echo "  Ports            : all UDP ports in these groups"
else
    echo "  Ports            : only $PORTS"
fi
echo ""
echo "The nftables ruleset will be regenerated (default-deny, scoped to the"
echo "above) and the relay + hourly health check will be enabled."
while true; do
    read -r -p "Apply? [y/N]: " ans
    ans="${ans,,}"
    if [ "$ans" = "y" ] || [ "$ans" = "yes" ]; then break; fi
    echo "Aborted — nothing was changed."
    exit 0
done

write_conf
apply_config
